# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=300)),
                ('message_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message_author', models.CharField(default='B', max_length=1)),
                ('message_gif', models.CharField(default='', max_length=200)),
                ('weather_temp', models.CharField(default='', max_length=8)),
                ('weather_temp_min', models.CharField(default='', max_length=8)),
                ('weather_humidity', models.CharField(default='', max_length=8)),
                ('weather_wind', models.CharField(default='', max_length=20)),
                ('weather_pressure', models.CharField(default='', max_length=20)),
                ('weather_img', models.CharField(default='', max_length=50)),
                ('weather_place', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('napis_text', models.CharField(max_length=200)),
                ('data_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_lat', models.CharField(default='', max_length=30)),
                ('user_lon', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
