# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20180113_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='message_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
