# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20180113_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
