# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_chat_message_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_gif',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
