# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20180114_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message_text',
            field=models.CharField(max_length=300),
        ),
    ]
